### ISSUE TITLE
Consider renaming the repository

### ISSUE THREAD

**Issue by unixorn** [cpea2506/zsh-config#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the name is awfully generic. Please consider renaming it to something descriptive, or even just name it after your github username.

Thanks!

**Comment by cpea2506** [comment]
Oh wow! I named it generally because it take me no time to think 😄. Now it has a new name, you can consider adding it to your collections.

Thanks!
